version: '3.8'
services:
    watchtower:
        restart: always
        container_name: watchtower
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        image: containrrr/watchtower
        env_file:
          - .env
